name: Reopen PRs under codereview-feraset
on:
  pull_request:
    types: [opened]

jobs:
  reauthor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Install GitHub CLI
        uses: cli/cli-action@v2

      - name: Reopen PR as codereview-feraset
        env:
          GH_TOKEN: ${{ secrets.CR_PAT }}   # PAT from codereview-feraset
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          if [ "$PR_AUTHOR" = "codereview-feraset" ]; then
            echo "Already authored by codereview-feraset."
            exit 0
          fi

          # Close the original PR
          gh pr close "$PR_NUMBER" --repo "$REPO" --comment "Reopening under @codereview-feraset"

          # Recreate PR under codereview-feraset
          gh pr create \
            --repo "$REPO" \
            --base "$BASE_REF" \
            --head "$HEAD_REF" \
            --title "Recreated PR" \
            --body "Auto-opened by codereview-feraset" \
            --draft

          # Grab new PR number and trigger Bugbot
          NEW_PR=$(gh pr list --repo "$REPO" --head "$HEAD_REF" --state open --json number -q '.[0].number')
          gh pr comment "$NEW_PR" --repo "$REPO" --body "bugbot run"
